### ISSUE TITLE
Invalid Version: https://registry.npmjs.org/@angular/core/-/core-4.1.3.tgz

### ISSUE THREAD

**Issue by bot101** [wangdicoder/angular-material-dashboard#6]
I followed the installation process as outliined in the readme and got this error message.

```
TypeError: Invalid Version: https://registry.npmjs.org/@angular/core/-/core-4.1.3.tgz
    at new SemVer (C:\Users\Alexander Orah\Desktop\Projects\ngtemplates\angular-material-dashboard\node_modules\semver\semver.js:293:11)
    at new Version (C:\Users\Alexander Orah\Desktop\Projects\ngtemplates\angular-material-dashboard\node_modules\@angular\cli\upgrade\version.js:23:36)
    at Function.assertAngularVersionIs2_3_1OrHigher (C:\Users\Alexander Orah\Desktop\Projects\ngtemplates\angular-material-dashboard\node_modules\@angular\cli\upgrade\version.js:80:23)
    at Class.run (C:\Users\Alexander Orah\Desktop\Projects\ngtemplates\angular-material-dashboard\node_modules\@angular\cli\commands\serve.js:95:27)
    at Class.Command.validateAndRun (C:\Users\Alexander Orah\Desktop\Projects\ngtemplates\angular-material-dashboard\node_modules\@angular\cli\ember-cli\lib\models\command.js:128:15)
    at C:\Users\Alexander Orah\Desktop\Projects\ngtemplates\angular-material-dashboard\node_modules\@angular\cli\ember-cli\lib\cli\cli.js:92:22
    at tryCatch (C:\Users\Alexander Orah\Desktop\Projects\ngtemplates\angular-material-dashboard\node_modules\rsvp\dist\rsvp.js:539:12)
    at invokeCallback (C:\Users\Alexander Orah\Desktop\Projects\ngtemplates\angular-material-dashboard\node_modules\rsvp\dist\rsvp.js:554:13)
    at C:\Users\Alexander Orah\Desktop\Projects\ngtemplates\angular-material-dashboard\node_modules\rsvp\dist\rsvp.js:629:16
    at flush (C:\Users\Alexander Orah\Desktop\Projects\ngtemplates\angular-material-dashboard\node_modules\rsvp\dist\rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

$ ng -v
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.2.6
node: 7.8.0
os: win32 x64
@angular/animations: 4.3.2
@angular/common: 4.3.2
@angular/compiler: 4.3.2
@angular/core: 4.3.2
@angular/forms: 4.3.2
@angular/http: 4.3.2
@angular/platform-browser: 4.3.2
@angular/platform-browser-dynamic: 4.3.2
@angular/router: 4.3.2
@angular/cli: 1.2.6
@angular/compiler-cli: 4.3.2
@angular/language-service: 4.3.2
```

**Comment by bot101** [comment]
Resolved it by following: https://stackoverflow.com/questions/44328652/ng-serve-erroring-after-npm-5-0-1-update-invalid-version.

Specifically, i did ` rm -f package-lock.json && npm install`, then installed missing dependencies manually
